### ISSUE TITLE
bid/ask size overlay with candle stick

### ISSUE THREAD

**Issue by nickleefly** [sdmiami/tradovate-custom-indicators#1]
hi, how do you show bid/ask volume with size overlay with candle like 
https://raw.githubusercontent.com/sdmiami/tradovate-custom-indicators/master/img/delta_histogram.png

**Comment by sdmiami** [comment]
In trading world it called "Footprint chart", it's one of the chart type that Tradovate provides on their platform, check out more info here --> [Bid Ask Chart ](https://tradovate.zendesk.com/hc/en-us/community/posts/360000700948-Bid-Ask-Chart-Display-Delta-Values-and-Volume-Imbalances)

**Comment by nickleefly** [comment]
@sdmiami yes I found the [Bid Ask Chart](https://tradovate.zendesk.com/hc/en-us/community/posts/360000700948-Bid-Ask-Chart-Display-Delta-Values-and-Volume-Imbalances), but after selecting bid-ask volume, and checked the chart setting below
i dont see it like what you have [here](https://github.com/sdmiami/tradovate-custom-indicators/blob/master/img/delta_histogram.png)
![image](https://user-images.githubusercontent.com/1024773/89125804-96d72b00-d513-11ea-8591-66b720a41a31.png)

**Comment by nickleefly** [comment]
I had to zoom in to see it, thanks man. I was using 30 min chart, thats why I didnt zoom in bigger enough.
